name: Deploy Python app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'geo-data-map'  
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
